import axios from "axios";
import type { NextPage } from "next";
import { getSession, useSession } from "next-auth/react";

import HomeTemplate from "@/app/components/templates/Home";
import LoadingTemplate from "@/app/components/templates/Loading";
import LoginTemplate from "@/app/components/templates/Login";
import Head from "next/head";

const Home: NextPage = ({ tasks }: any) => {
  tasks = JSON.parse(tasks);
  const { data: session, status } = useSession();
  if (status === "loading") return <LoadingTemplate />;
  if (!session) return <LoginTemplate />;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Sofia+Sans:wght@200;300;400&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400&display=swap"
          rel="stylesheet"></link>
      </Head>
      <body>
        <HomeTemplate tasks={tasks} />
      </body>
    </>
  );
};

export async function getServerSideProps({ req }: { req: any }) {
  try {
    const session = await getSession({ req });
    let tasks;
    if (session?.user) {
      const res = await axios.post(`${process.env.SITE_URL}/api/lists/home`, {
        ownerId: session.user.id,
      });
      tasks = JSON.stringify(res.data.payload || []);
    } else {
      tasks = "[]";
    }
    return { props: { tasks } };
  } catch (error) {
    console.error(error);
    return { props: { tasks: "[]" } };
  }
}

export default Home;
